version: '3.3'

services:
  db:
    image: mysql:5.7
    # restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    # restart: always
    ports:
      - 8080:8080

volumes:
  mysql-data:
